I fixed the class Genre, so that rap.songs #=> [ninety_nine_problems, lucifer], else it returns this error message: NameError: undefined local variable or method `song' for #<Song:0x007ff572120ba0> 	from (irb):7:in `initialize' 	from (irb):54:in `new'